### PR TITLE
Introduce new `apply` options to make use of hunter groups

### PR DESCRIPTION
**Pull request by Womblue**
This PR introduces three new options for the `apply` command.

### `--detect-identity`

This option enables Profile to search through the Hunter groups of all nodes. If a given node has a group name which matches an identity for the currently configured type, then that identity will be applied to the node.

With the introduction of this option, including an identity with the `apply` command is no longer mandatory. One may still be provided, and it will be used as a backup for any nodes that do not have a valid identity within their set of Hunter groups.

If a node has a set of groups with multiple valid identities (e.g. `[login,compute,master,worker]`) then the first valid identity will be used. In general, this situation should be avoided regardless.

### `--groups`, `-g`

When this option is used, the list of given names will instead be used to search through the list of groups for each node, including each node in the application if one of its groups matches one of the given names. For example `profile apply my_nodes compute -g` would apply the `compute` identity to all nodes with the Hunter group `my_nodes`.

### `--dry-run`

With this option enabled, `apply` will not actually start the application process for any nodes. Instead, it will print to the terminal which identity would be applied to each given node if you were to run the command without `--dry-run`. Given there are now multiple ways to specify which nodes and identities are being applied, this command is useful to ensure you've got everything set up correctly

## Testing
By creating three dummy nodes as such:

- `node01`, groups: `login`, `test_a`, `test_b`
- `node02`, groups: `compute`, `test_a`
- `node03`, groups: `test_a`

The functionality of each of these new options may be tested.

To establish that the `--dry-run` option works as expected:
```
$ profile apply node01 login --dry-run
Node 'node01' will be applied with identity 'login'
```
To establish that `--detect-identity` works as expected:
```
$ profile apply node01,node02 --detect-identity --dry-run
Node 'node01' will be applied with identity 'login'
Node 'node02' will be applied with identity 'compute'

$ profile apply node01,node02,node03 --detect-identity --dry-run
profile: Could not determine an identity for the following nodes: node03
Either provide a default identity, or add an identity to their set of Hunter groups.

$ profile apply node01,node02,node03 compute --detect-identity --dry-run
Node 'node01' will be applied with identity 'login'
Node 'node02' will be applied with identity 'compute'
Node 'node03' will be applied with identity 'compute'
```
To establish that `--groups` (`-g`) works as expected:
```
$ profile apply test_b login -g --dry-run
Node 'node01' will be applied with identity 'login'

$ profile apply test_z login -g --dry-run
profile: No nodes found in the given group(s)
```

Catch-all test which utilises all three new options:
```
$ profile apply test_a compute -g --detect-identity --dry-run
Node 'node01' will be applied with identity 'login'
Node 'node02' will be applied with identity 'compute'
Node 'node03' will be applied with identity 'compute'
```

### CODE REVIEW

**Comment by Womblue** [comment]
Added another small change to address an (apparently long-standing) issue in which the type state wasn't being correctly recorded.

**Comment by Womblue** [comment]
The current implementation is for `apply --detect-identity` to add all nodes to the queue so that the queue manager can sort which ones have met their dependencies and choose which to apply (since before this PR there's never been a way to use `apply` to apply different nodes with different identities in one command.

I can look into getting nodes with dependencies already met applied immediately since I do agree in retrospect that having them in the queue is misleading since that generally implies that they have unmet dependencies.

**Comment by ColonelPanicks** [comment]
I see, so it applies in a different manner to a regular apply? That makes sense but it can be confusing visually more than anything else.

I appreciate that this is a different condition for apply to deal with as it's never had to deal with more than one identity at once in it's command so some investigation would be useful to make it work "as expected". I can see that it'd be difficult to know which ones to apply "first" so it might just be a matter of sorting the output to be clear that all of these things aren't necessarily queued but are being "processed" by the queue. Perhaps by stating what identities will be applied to what and to check the output of `list` for status? (bonus if we can consolidate that output such that it lists the nodes in one line for each identity)

**Comment by ColonelPanicks** [comment]
This seems to get confused if nodes are in any state except `available`. Is this expected behaviour? 

```
[flight@gateway1 ~]$ flight profile list
┌──────────┬──────────┬──────────┐
│ Node     │ Identity │ Status   │
├──────────┼──────────┼──────────┤
│ gateway1 │ login    │ complete │
│ node01   │ compute  │ complete │
│ node02   │ compute  │ complete │
└──────────┴──────────┴──────────┘
[flight@gateway1 ~]$ flight hunter list
┌──────────┬──────────────────────────────────┬──────────────┬─────────────────────┬──────────┐
│ ID       │ Hostname                         │ IP           │ Groups              │ Label    │
├──────────┼──────────────────────────────────┼──────────────┼─────────────────────┼──────────┤
│ 640a0101 │ node01.proftest1.alces.network   │ 10.100.1.1   │ all, compute, nodes │ node01   │
│ 640a6500 │ gateway1.proftest1.alces.network │ 10.100.0.101 │ all, login          │ gateway1 │
│ 640a0201 │ node02.proftest1.alces.network   │ 10.100.1.2   │ all, compute, nodes │ node02   │
└──────────┴──────────────────────────────────┴──────────────┴─────────────────────┴──────────┘
[flight@gateway1 ~]$ flight profile apply -g all --detect-identity --dry-run
profile: No nodes found in the given group(s)
```

**Comment by Womblue** [comment]
Yep, it looks like there's an issue where the groups weren't being preserved after nodes were generated for Profile, the latest version of the branch should fix the issue (but profile will need its nodes cleared out)

**Comment by ColonelPanicks** [comment]
Does this potentially cause issues with data parity if node groups are changed in hunter? Have we always stored groups in profile?

**Comment by Womblue** [comment]
It would do, yes, because nodes in profile and nodes in hunter are separate things. The profile nodes are created based on data from the hunter nodes. Hunter groups were not previously stored by profile at all, so if you create a Profile node and later modify the Hunter groups of that node (in Hunter) then the node in Profile will NOT be updated to reflect this change.

**Comment by ColonelPanicks** [comment]
Fair enough, I suppose that's okay because if nodes are deleted from hunter it would also create some data parity issues. Perhaps this is a separate thing to investigate for consistency to ensure we handle orphaned things properly (e.g. warning/notifying users of that). 

I'll pull and test your changes, if that works as expected then will be happy to merge. Will report back shortly.

**Comment by Womblue** [comment]
I do see what you mean - it'd definitely be feasible to have a shared path where nodes are stored which both Profile and Hunter could get data from (for example) but it depends on how closely tied we want the two tools to be.

**Comment by ColonelPanicks** [comment]
This has definitely been discussed previously and is a little out-of-scope for this PR so I'll leave this discussion with the thought that, if profile is set to `use_hunter` then, it is coupled so using the hunter inventory directly doesn't seem wrong to me

**Comment by Womblue** [comment]
I've spent some time looking into the way that the new apply option puts all nodes into the queue, and I think it feels like something to solve alongside the planned improvements to the queue monitoring system (i.e. having the queue be updated at more specific times instead of just 5s intervals), perhaps Jack will have some other opinions when he reviews the PR but I'm wary that the script for the apply command is on the verge of becoming a little messy and over-complicated. You can work around the queue delay at the moment by including the identity name you want to apply in the apply command, for example:

```
profile apply node01,node02,node03 --detect-identity
```
will move all 3 nodes into the queue for their detected identity (assuming they all have one), however:
```
profile apply node01,node02,node03 <identity> --detect-identity
```
will apply the node(s) with identity <identity> immediately (bypassing the queue) and move all other nodes into the queue

**Comment by ColonelPanicks** [comment]
I see, that provides some extra clarity on it however I think what we can do for now is just handle the messaging in the use-case of detect-identity in a similar way to what was [mentioned here](https://github.com/openflighthpc/flight-profile/pull/119#issuecomment-1881038745). Does that seem reasonably possible?

Larger changes to how the queues work and detects what can/can't be immediately applied is a larger task I think we can approach later.

**Comment by ColonelPanicks** [comment]
With recent changes this LGTM!

**Review by VoxSecundus — APPROVED** [review]
I've pushed a commit to apply `rubocop` linting; this LGTM otherwise :shipit:

**Pull request merged**
